[tox]
envlist = py39, py310, py311
isolated_build = True

[testenv]
allowlist_externals = poetry
commands =
    poetry install
    poetry run coverage run -m pytest tests/
    poetry run coverage report -m
    poetry run coverage xml


[coverage:run]
source = src

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    if self.debug:
    raise NotImplementedError
    if __name__ == .__main__.:
